-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL
CREATE TABLE ana_clienti (
	id int(11) NULL,
	cognome varchar(100) NULL,
	nome varchar(100) NULL,
	indirizzo varchar(1000) NULL,
	citta varchar(200) NULL,
	cap int(11) NULL,
	telefono1 varchar(50) NULL,
	telefono2 varchar(50) NULL,
	note varchar(4000) NULL,
	codice_fiscale varchar(16) NULL,
	mail varchar(200) NULL,
	cliente2 varchar(100) NULL,
	codice_fiscale2 varchar(16) NULL,
	mail2 varchar(100) NULL,
	citofono varchar(100) NULL,
	piano varchar(100) NULL,
	scala varchar(1000) NULL,
	porta varchar(1000) NULL,
	cassetta_postale varchar(500) NULL,
	fl_regolamento tinyint(1) NULL,
	fl_sanitario tinyint(1) NULL,
	fl_privacy tinyint(1) NULL,
	valutazione int(11) NULL,
	note_valutazione varchar(4000) NULL,
	veterinario varchar(100) NULL,
	tel_veterinario varchar(100) NULL
);


-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL
CREATE TABLE ana_gatti (
	id int(11) NULL,
	id_cliente int(11) NULL,
	nome_gatto varchar(100) NULL,
	razza varchar(100) NULL,
	mantello varchar(100) NULL,
	sesso varchar(1) NULL,
	microchip varchar(100) NULL,
	fl_sterilizzato varchar(1) NULL,
	medicine varchar(1) NULL,
	dt_scad_vaccino date NULL,
	dt_fiv_felv date NULL,
	fl_abilitato varchar(1) NULL
);


-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL
CREATE TABLE preventivi (
	id_preventivo int(11) NULL,
	dt_scadenza date NULL,
	id_cliente int(11) NULL,
	dal date NULL,
	al date NULL,
	dt_check_in date NULL,
	tm_check_in time NULL,
	dt_check_out date NULL,
	tm_check_out time NULL,
	giorni int(11) NULL,
	sconto int(11) NULL,
	importo_sconto float NULL,
	fl_status varchar(2) NULL,
	cap_50 float NULL,
	cap_30 float NULL,
	cap_20 float NULL,
	totale_preventivo float NULL
);


-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL
CREATE TABLE servizi (
	id int(11) NULL,
	servizio varchar(500) NULL,
	prezzo float NULL,
	fl_enable varchar(1) NULL
);

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL
CREATE TABLE status (
	id int(11) NULL,
	status varchar(500) NULL,
	ordine int NULL,
	fl_enable varchar(1) NULL
)