/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistrazioneRouteImport } from './routes/registrazione'
import { Route as NuovaRouteImport } from './routes/nuova'
import { Route as MieSegnalazioniRouteImport } from './routes/mie-segnalazioni'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const RegistrazioneRoute = RegistrazioneRouteImport.update({
  id: '/registrazione',
  path: '/registrazione',
  getParentRoute: () => rootRouteImport,
} as any)
const NuovaRoute = NuovaRouteImport.update({
  id: '/nuova',
  path: '/nuova',
  getParentRoute: () => rootRouteImport,
} as any)
const MieSegnalazioniRoute = MieSegnalazioniRouteImport.update({
  id: '/mie-segnalazioni',
  path: '/mie-segnalazioni',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/mie-segnalazioni': typeof MieSegnalazioniRoute
  '/nuova': typeof NuovaRoute
  '/registrazione': typeof RegistrazioneRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/mie-segnalazioni': typeof MieSegnalazioniRoute
  '/nuova': typeof NuovaRoute
  '/registrazione': typeof RegistrazioneRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/mie-segnalazioni': typeof MieSegnalazioniRoute
  '/nuova': typeof NuovaRoute
  '/registrazione': typeof RegistrazioneRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/feed'
    | '/login'
    | '/manager'
    | '/mie-segnalazioni'
    | '/nuova'
    | '/registrazione'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/feed'
    | '/login'
    | '/manager'
    | '/mie-segnalazioni'
    | '/nuova'
    | '/registrazione'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/feed'
    | '/login'
    | '/manager'
    | '/mie-segnalazioni'
    | '/nuova'
    | '/registrazione'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  FeedRoute: typeof FeedRoute
  LoginRoute: typeof LoginRoute
  ManagerRoute: typeof ManagerRoute
  MieSegnalazioniRoute: typeof MieSegnalazioniRoute
  NuovaRoute: typeof NuovaRoute
  RegistrazioneRoute: typeof RegistrazioneRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registrazione': {
      id: '/registrazione'
      path: '/registrazione'
      fullPath: '/registrazione'
      preLoaderRoute: typeof RegistrazioneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nuova': {
      id: '/nuova'
      path: '/nuova'
      fullPath: '/nuova'
      preLoaderRoute: typeof NuovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mie-segnalazioni': {
      id: '/mie-segnalazioni'
      path: '/mie-segnalazioni'
      fullPath: '/mie-segnalazioni'
      preLoaderRoute: typeof MieSegnalazioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  FeedRoute: FeedRoute,
  LoginRoute: LoginRoute,
  ManagerRoute: ManagerRoute,
  MieSegnalazioniRoute: MieSegnalazioniRoute,
  NuovaRoute: NuovaRoute,
  RegistrazioneRoute: RegistrazioneRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
